/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author aluno.saolucas
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        btnEncerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        mnCadCliente = new javax.swing.JMenuItem();
        mnCadPet = new javax.swing.JMenuItem();
        mnCadFuncionario = new javax.swing.JMenuItem();
        mnConsulta = new javax.swing.JMenu();
        mnConCliente = new javax.swing.JMenuItem();
        mnConPet = new javax.swing.JMenuItem();
        mnConVendas = new javax.swing.JMenuItem();
        mnItens = new javax.swing.JMenu();
        mnInventario = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnEncerrar.setText("Encerrar");
        btnEncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEncerrarMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgPetMenu256px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEncerrar)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addComponent(btnEncerrar)
                .addContainerGap())
        );

        mnCadastro.setText("Cadastro");

        mnCadCliente.setText("Cliente");
        mnCadCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnCadClienteMouseClicked(evt);
            }
        });
        mnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadClienteActionPerformed(evt);
            }
        });
        mnCadastro.add(mnCadCliente);

        mnCadPet.setText("Pet");
        mnCadPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnCadPetMouseClicked(evt);
            }
        });
        mnCadastro.add(mnCadPet);

        mnCadFuncionario.setText("Funcionario");
        mnCadFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnCadFuncionarioMouseClicked(evt);
            }
        });
        mnCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadFuncionarioActionPerformed(evt);
            }
        });
        mnCadastro.add(mnCadFuncionario);

        jMenuBar1.add(mnCadastro);

        mnConsulta.setText("Consulta");

        mnConCliente.setText("Cliente");
        mnConsulta.add(mnConCliente);

        mnConPet.setText("Pet");
        mnConsulta.add(mnConPet);

        mnConVendas.setText("Vendas");
        mnConsulta.add(mnConVendas);

        jMenuBar1.add(mnConsulta);

        mnItens.setText("Itens");

        mnInventario.setText("Inventario");
        mnItens.add(mnInventario);

        jMenuBar1.add(mnItens);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCadClienteMouseClicked
        FrCadCliente telaCadCliente = new FrCadCliente(this, rootPaneCheckingEnabled);

        telaCadCliente.setVisible(true);
    }//GEN-LAST:event_mnCadClienteMouseClicked

    private void mnCadPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCadPetMouseClicked
        FrCadPet telaCadPet = new FrCadPet(this, rootPaneCheckingEnabled);

        telaCadPet.setVisible(true);
    }//GEN-LAST:event_mnCadPetMouseClicked

    private void mnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCadClienteActionPerformed

    private void mnCadFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCadFuncionarioMouseClicked
       
    }//GEN-LAST:event_mnCadFuncionarioMouseClicked

    private void mnCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadFuncionarioActionPerformed
        FrCadFuncionario telaCadFuncionario = new FrCadFuncionario(this, rootPaneCheckingEnabled);

        telaCadFuncionario.setVisible(true);
    }//GEN-LAST:event_mnCadFuncionarioActionPerformed

    private void btnEncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnEncerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnCadCliente;
    private javax.swing.JMenuItem mnCadFuncionario;
    private javax.swing.JMenuItem mnCadPet;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenuItem mnConCliente;
    private javax.swing.JMenuItem mnConPet;
    private javax.swing.JMenuItem mnConVendas;
    private javax.swing.JMenu mnConsulta;
    private javax.swing.JMenuItem mnInventario;
    private javax.swing.JMenu mnItens;
    // End of variables declaration//GEN-END:variables
}
